
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class AddWard extends javax.swing.JFrame {

    /**
     * Creates new form AddEmployee
     */
    myDBCon dbCon;
    ResultSet rs;

    public AddWard() {
        initComponents();
        this.setLocationRelativeTo(null); // center form in screen 
        // set all error labels to invisible
        lblWardIdError.setVisible(false);
        lblWardNameError.setVisible(false);
        lblWardLocError.setVisible(false);

        dbCon = new myDBCon();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtWardId = new javax.swing.JTextField();
        txtWardName = new javax.swing.JTextField();
        txtWardLoc = new javax.swing.JTextField();
        btnAddNewWard = new javax.swing.JButton();
        lblWardIdError = new javax.swing.JLabel();
        lblWardLocError = new javax.swing.JLabel();
        lblWardNameError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Employee");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add New Ward");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("WARD ID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("WARD NAME:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("WARD LOCATION:");

        txtWardId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtWardName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtWardLoc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtWardLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWardLocActionPerformed(evt);
            }
        });

        btnAddNewWard.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddNewWard.setText("Add New");
        btnAddNewWard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewWardActionPerformed(evt);
            }
        });

        lblWardIdError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblWardIdError.setForeground(new java.awt.Color(255, 0, 0));
        lblWardIdError.setText("error label");

        lblWardLocError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblWardLocError.setForeground(new java.awt.Color(255, 0, 0));
        lblWardLocError.setText("error label");

        lblWardNameError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblWardNameError.setForeground(new java.awt.Color(255, 0, 0));
        lblWardNameError.setText("error label");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtWardName, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(txtWardLoc))
                            .addComponent(txtWardId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblWardNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblWardLocError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblWardIdError, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddNewWard)
                .addGap(271, 271, 271))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtWardId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWardIdError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtWardName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWardNameError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtWardLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWardLocError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddNewWard)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtWardLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWardLocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWardLocActionPerformed

    // verify valid entry of integer values
    public boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    // verify valid entry of double values
    public boolean isDouble(String s) {
        try {
            Double.parseDouble(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    void clearErrorLabels() { // clear all labels used to display error messages 
        lblWardIdError.setText("");
        lblWardIdError.setVisible(false);
        lblWardNameError.setText("");
        lblWardNameError.setVisible(false);
        lblWardLocError.setText("");
        lblWardLocError.setVisible(false);

    }

    // validate all user entry before sending new employee details to DB
    boolean isValidData() {
        clearErrorLabels();
        boolean result = true; // assume all details are true, set to false if otherwise 
        // you need to check format deails and make sure they are consistent with DB 
        if (txtWardId.getText().trim().isEmpty() || !isInteger(txtWardId.getText().trim())) {
            if (txtWardId.getText().trim().isEmpty()) {
                lblWardIdError.setText("Invalid. Cannot be empty.");
            } else if (!isInteger(txtWardId.getText().trim())) {
                lblWardIdError.setText("Invalid. Must be integer.");
            }
            lblWardIdError.setVisible(true);
            result = false;
        }

        if (txtWardName.getText().trim().isEmpty() || (txtWardName.getText().trim().length() > 30)) {
            if (txtWardName.getText().trim().isEmpty()) {
                lblWardNameError.setText("Invalid. Cannot be empty.");
            } else if ((txtWardName.getText().trim().length() > 30)) {
                lblWardNameError.setText("Invalid. Must be <= 30 chars.");
            }
            lblWardNameError.setVisible(true);
            result = false;
        }

        if (txtWardLoc.getText().trim().isEmpty() || (txtWardLoc.getText().trim().length() > 30)) {
            if (txtWardLoc.getText().trim().isEmpty()) {
                lblWardLocError.setText("Invalid. Cannot be empty.");
            } else if (txtWardLoc.getText().trim().length() > 30) {
                lblWardLocError.setText("Invalid. Must be <= 30 chars.");
            }
            lblWardLocError.setVisible(true);
            result = false;
        }

        return result;
    }

    void clearInputBoxes() { // clear for every new entry 
        txtWardId.setText("");
        txtWardName.setText("");
        txtWardLoc.setText("");
    }

    private boolean isDuplicate(int wardid) throws SQLException {
        boolean isduplicate = false;
        String stmtSQL = "SELECT ward_id FROM ward WHERE ward_id = " + wardid;
        rs = dbCon.executeStatement(stmtSQL);
        // isBeforeFirst() returns false if there are no data in the resultset
        isduplicate = rs.isBeforeFirst();

        return isduplicate;
    }
    private void btnAddNewWardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewWardActionPerformed
        // TODO add your handling code here:

        try {
           // you need also to verify that the empno is unique and not duplicate 
              
            if (isValidData() && !isDuplicate(Integer.parseInt(txtWardId.getText().trim()))) {
              
                // if new employee details are valid, then add new employee to DB
                String prepSQL = "INSERT INTO ward (ward_id, ward_name, ward_location) VALUES (" 
                        + txtWardId.getText().trim() + ", "
                        + "'" + txtWardName.getText().toUpperCase() 
                        + "', "  + "'" + txtWardLoc.getText().toUpperCase() 
                        + "')";

                int result = dbCon.executePrepared(prepSQL);
                //if succesfull
                if (result > 0) {

                    javax.swing.JLabel label = new javax.swing.JLabel("New ward added successfully.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    clearInputBoxes();
                }  }
                else { //validation error
                if (!isDuplicate(Integer.parseInt(txtWardId.getText().trim()))) {
                    javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
                } else { //employee already exists
                    javax.swing.JLabel label = new javax.swing.JLabel("Ward Already exists. Use a different number.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.INFORMATION_MESSAGE);
                    
                }

            }
        } catch (SQLException e) {
            //error adding employee
            JOptionPane.showMessageDialog(null, "Error adding new ward."+e.getMessage());
        }
    }//GEN-LAST:event_btnAddNewWardActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewWard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblWardIdError;
    private javax.swing.JLabel lblWardLocError;
    private javax.swing.JLabel lblWardNameError;
    private javax.swing.JTextField txtWardId;
    private javax.swing.JTextField txtWardLoc;
    private javax.swing.JTextField txtWardName;
    // End of variables declaration//GEN-END:variables
}
