
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class AddPatient extends javax.swing.JFrame {

    myDBCon dbCon;
    ResultSet rs;

    public AddPatient() {
         
        initComponents();
        this.setTitle("Add Patient");
         setSize(800, 330);
        this.setLocationRelativeTo(null); // center form in screen 
        // set all error labels to invisible
        lblPatIdError.setVisible(false);
        lblFnameError.setVisible(false);
        lblLnameError.setVisible(false);
        lblDateOfBirthError.setVisible(false);


        try {
            dbCon = new myDBCon();
            rs = dbCon.executeStatement("SELECT ward_id FROM ward ORDER BY ward_id ASC");
            // populate ward combo box
            while (rs.next()) {
                cmbWard.addItem(rs.getString("ward_id"));
            }
            rs.close();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPatId = new javax.swing.JTextField();
        txtFname = new javax.swing.JTextField();
        txtLname = new javax.swing.JTextField();
        cmbWard = new javax.swing.JComboBox<>();
        btnAddNewPat = new javax.swing.JButton();
        lblPatIdError = new javax.swing.JLabel();
        lblLnameError = new javax.swing.JLabel();
        lblFnameError = new javax.swing.JLabel();
        lblDateOfBirthError = new javax.swing.JLabel();
        ftxtDateOfBirth = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Employee");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add New Patient");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 8, 782, 44);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("PATIENT ID:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(192, 62, 115, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("FIRST NAME:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(188, 98, 119, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("LAST NAME:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(198, 134, 109, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("WARD ID:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(214, 204, 93, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("DATE OF BIRTH:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(159, 171, 148, 22);

        txtPatId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtPatId);
        txtPatId.setBounds(325, 58, 100, 30);

        txtFname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtFname);
        txtFname.setBounds(325, 94, 248, 30);

        txtLname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtLname);
        txtLname.setBounds(325, 130, 248, 30);

        cmbWard.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(cmbWard);
        cmbWard.setBounds(325, 204, 80, 32);

        btnAddNewPat.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddNewPat.setText("Add New");
        btnAddNewPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewPatActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddNewPat);
        btnAddNewPat.setBounds(325, 250, 170, 45);

        lblPatIdError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblPatIdError.setForeground(new java.awt.Color(255, 0, 0));
        lblPatIdError.setText("error label");
        getContentPane().add(lblPatIdError);
        lblPatIdError.setBounds(586, 66, 196, 22);

        lblLnameError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblLnameError.setForeground(new java.awt.Color(255, 0, 0));
        lblLnameError.setText("error label");
        getContentPane().add(lblLnameError);
        lblLnameError.setBounds(586, 134, 196, 22);

        lblFnameError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblFnameError.setForeground(new java.awt.Color(255, 0, 0));
        lblFnameError.setText("error label");
        getContentPane().add(lblFnameError);
        lblFnameError.setBounds(586, 98, 196, 22);

        lblDateOfBirthError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblDateOfBirthError.setForeground(new java.awt.Color(255, 0, 0));
        lblDateOfBirthError.setText("error label");
        getContentPane().add(lblDateOfBirthError);
        lblDateOfBirthError.setBounds(586, 174, 196, 22);

        ftxtDateOfBirth.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d-MMM-yyyy"))));
        ftxtDateOfBirth.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ftxtDateOfBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxtDateOfBirthActionPerformed(evt);
            }
        });
        getContentPane().add(ftxtDateOfBirth);
        ftxtDateOfBirth.setBounds(325, 166, 150, 32);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(11, 86, 0, 0);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitaldbms/patient-icon.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(17, 70, 128, 128);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLnameActionPerformed

    // verify valid entry of integer values
    public boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    // verify valid entry of double values
    public boolean isDouble(String s) {
        try {
            Double.parseDouble(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    void clearErrorLabels() { // clear all labels used to display error messages 
        lblPatIdError.setText("");
        lblPatIdError.setVisible(false);
        lblFnameError.setText("");
        lblFnameError.setVisible(false);
        lblLnameError.setText("");
        lblLnameError.setVisible(false);
        lblDateOfBirthError.setText("");
        lblDateOfBirthError.setVisible(false);

    }

    // validate all user entry before sending new employee details to DB
    boolean isValidData() {
        clearErrorLabels();
        boolean result = true; // assume all details are true, set to false if otherwise 
        // you need to check format deails and make sure they are consistent with DB 
        if (txtPatId.getText().trim().isEmpty() || !isInteger(txtPatId.getText().trim())) {
            if (txtPatId.getText().trim().isEmpty()) {
                lblPatIdError.setText("Invalid. Cannot be empty.");
            } else if (!isInteger(txtPatId.getText().trim())) {
                lblPatIdError.setText("Invalid. Must be integer.");
            }
            lblPatIdError.setVisible(true);
            result = false;
        }

        if (txtFname.getText().trim().isEmpty() || (txtFname.getText().trim().length() > 30)) {
            if (txtFname.getText().trim().isEmpty()) {
                lblFnameError.setText("Invalid. Cannot be empty.");
            } else if ((txtFname.getText().trim().length() > 30)) {
                lblFnameError.setText("Invalid. Must be <= 30 chars.");
            }
            lblFnameError.setVisible(true);
            result = false;
        }

        if (txtLname.getText().trim().isEmpty() || (txtLname.getText().trim().length() > 30)) {
            if (txtLname.getText().trim().isEmpty()) {
                lblLnameError.setText("Invalid. Cannot be empty.");
            } else if (txtLname.getText().trim().length() > 30) {
                lblLnameError.setText("Invalid. Must be <= 30 chars.");
            }
            lblLnameError.setVisible(true);
            result = false;
        }

        if (ftxtDateOfBirth.getText().trim().isEmpty()) {
            lblDateOfBirthError.setText("Invalid. Cannot be empty.");
            lblDateOfBirthError.setVisible(true);
            result = false;
        }

        return result;
    }

    void clearInputBoxes() { // clear for every new entry 
        txtPatId.setText("");
        txtFname.setText("");
        txtLname.setText("");
        ftxtDateOfBirth.setText("");
        cmbWard.setSelectedIndex(0);
    }

    private boolean isDuplicate(int patid) throws SQLException {
        boolean isduplicate = false;
        String stmtSQL = "SELECT patient_id FROM patient WHERE patient_id = " + patid;
        rs = dbCon.executeStatement(stmtSQL);
        // isBeforeFirst() returns false if there are no data in the resultset
        isduplicate = rs.isBeforeFirst();

        return isduplicate;
    }
    private void btnAddNewPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewPatActionPerformed
        // TODO add your handling code here:

        try {
           // you need also to verify that the empno is unique and not duplicate 
              
            if (isValidData() && !isDuplicate(Integer.parseInt(txtPatId.getText().trim()))) {
              
                // if new employee details are valid, then add new employee to DB
                String prepSQL = "INSERT INTO patient (patient_id, fname, lname, date_of_birth, ward_id) VALUES (" 
                        + txtPatId.getText().trim() + ", "
                        + "'" + txtFname.getText().toUpperCase() 
                        + "', '"  + txtLname.getText().toUpperCase() 
                        + "', '" + ftxtDateOfBirth.getText().trim()
                        + "', " + cmbWard.getSelectedItem().toString() + " )";

                int result = dbCon.executePrepared(prepSQL);
                //if succesfull
                if (result > 0) {

                    javax.swing.JLabel label = new javax.swing.JLabel("New patient added successfully.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    clearInputBoxes();
                }  }
                else { //validation error
                if (!isDuplicate(Integer.parseInt(txtPatId.getText().trim()))) {
                    javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
                } else { //employee already exists
                    javax.swing.JLabel label = new javax.swing.JLabel("Patient_id Already exists. Use a different number.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.INFORMATION_MESSAGE);
                    
                }

            }
        } catch (SQLException e) {
            //error adding employee
            JOptionPane.showMessageDialog(null, "Error adding new patient."+e.getMessage());
        }
    }//GEN-LAST:event_btnAddNewPatActionPerformed

    private void ftxtDateOfBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxtDateOfBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxtDateOfBirthActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewPat;
    private javax.swing.JComboBox<String> cmbWard;
    private javax.swing.JFormattedTextField ftxtDateOfBirth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblDateOfBirthError;
    private javax.swing.JLabel lblFnameError;
    private javax.swing.JLabel lblLnameError;
    private javax.swing.JLabel lblPatIdError;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtPatId;
    // End of variables declaration//GEN-END:variables
}
